# Generated by Django 4.2.23 on 2025-11-26 11:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("horilla_core", "0002_horillaaboutsystem"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorillaUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "permissions": (
                    ("can_view_profile", "Can View Profile"),
                    ("can_change_profile", "Can Change Profile"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.AlterField(
            model_name="businesshour",
            name="week_days",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("sun", "Sunday"),
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                ],
                max_length=27,
            ),
        ),
        migrations.AlterField(
            model_name="businesshour",
            name="week_start_day",
            field=models.CharField(
                choices=[
                    ("sun", "Sunday"),
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                ],
                default="monday",
                help_text="Week Start Day",
                max_length=10,
                verbose_name="Week Start Day",
            ),
        ),
        migrations.AlterField(
            model_name="exportschedule",
            name="weekday",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sun", "Sunday"),
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                ],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fiscalyear",
            name="week_start_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sun", "Sunday"),
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                ],
                max_length=20,
                null=True,
                verbose_name="Week Start Day",
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="monthly_day_of_week",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sun", "Sunday"),
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                ],
                max_length=10,
                null=True,
                verbose_name="Day of Week",
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="weekly_days",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("sun", "Sunday"),
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                ],
                max_length=27,
                verbose_name="Weekly Days",
            ),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="yearly_day_of_week",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sun", "Sunday"),
                    ("mon", "Monday"),
                    ("tue", "Tuesday"),
                    ("wed", "Wednesday"),
                    ("thu", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                ],
                max_length=10,
                null=True,
                verbose_name="Day of Week",
            ),
        ),
    ]
