# Generated by Django 4.2.23 on 2025-11-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("horilla_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentcriteria",
            name="operator",
            field=models.CharField(
                choices=[
                    ("equals", "Equals"),
                    ("not_equals", "Not Equals"),
                    ("contains", "Contains"),
                    ("not_contains", "Does Not Contain"),
                    ("starts_with", "Starts With"),
                    ("ends_with", "Ends With"),
                    ("greater_than", "Greater Than"),
                    ("greater_than_equal", "Greater Than or Equal"),
                    ("less_than", "Less Than"),
                    ("less_than_equal", "Less Than or Equal"),
                    ("is_empty", "Is Empty"),
                    ("is_not_empty", "Is Not Empty"),
                ],
                max_length=50,
                verbose_name="Operator",
            ),
        ),
    ]
