# Generated by Django 4.2.23 on 2025-11-27 11:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="country",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="Country"
            ),
        ),
    ]
