"""
Django settings for horilla project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

# -----------------------------------------------------------------------------
#   Environment & Configuration Management
# -----------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent.parent
BASE_APP_DIR = BASE_DIR / "horilla"


# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, True),
    ENVIRONMENT=(str, "development"),  # production/staging/development
    SECRET_KEY=(str, "django-insecure-default-key"),
    ALLOWED_HOSTS=(list, ["*"]),
    CSRF_TRUSTED_ORIGINS=(list, ["http://localhost:8000"]),
)

# Read from .env file if exists
env_file = BASE_DIR / ".env"
if env_file.exists():
    env.read_env(str(env_file), overwrite=True)

# Environment variables
DEBUG = env("DEBUG")
ENVIRONMENT = env("ENVIRONMENT")
SECRET_KEY = env("SECRET_KEY")
ALLOWED_HOSTS = env("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")

# -----------------------------------------------------------------------------
#  Installed Apps Organization
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    # Core Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    # Daphne must come before staticfiles
    "daphne",
    # Core Django static app
    "django.contrib.staticfiles",
    # Third-party apps
    "channels",
    "whitenoise.runserver_nostatic",
    "colorfield",
    "djmoney",
    "django_filters",
    "django_summernote",
    "login_history",
    "auditlog",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_yasg",
    # Horilla apps
    "horilla_core",
    "horilla_generics",
    "horilla_reports",
    "horilla_dashboard",
    "horilla_utils",
    "horilla_notifications",
    "horilla_mail",
    "horilla_keys",
]


# -----------------------------------------------------------------------------
# REST Framework Configuration
# -----------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

# JWT Settings
SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# -----------------------------------------------------------------------------
# Middleware Configuration
# -----------------------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "horilla_core.middlewares.TimezoneMiddleware",
    "horilla_core.middlewares.ActiveCompanyMiddleware",
    "horilla_core.middlewares.HorillaExceptionMiddleware",
    "horilla_core.middlewares.Horilla405Middleware",
    "horilla_core.middlewares.SVGSecurityMiddleware",
    "horilla_core.middlewares.HTMXRedirectMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "horilla_utils.middlewares.ThreadLocalMiddleware",
]


ROOT_URLCONF = "horilla.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "horilla.context_processors.company_list",
                "horilla.context_processors.allowed_languages",
                "horilla.context_processors.recently_viewed_items",
                "horilla.context_processors.unread_notifications",
                "horilla.context_processors.menu_context_processor",
                "horilla.context_processors.currency_context",
            ],
        },
    },
]

WSGI_APPLICATION = "horilla.wsgi.application"
ASGI_APPLICATION = "horilla.asgi.application"


# -----------------------------------------------------------------------------
# Channels
# -----------------------------------------------------------------------------
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
        # "BACKEND": "channels_redis.core.RedisChannelLayer",
        # "CONFIG": {
        #     "hosts": [("127.0.0.1", 6379)],  # Redis server
        # },
    },
}


# -----------------------------------------------------------------------------
# Database and Performance Enhancements
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# -----------------------------------------------------------------------------
if env("DATABASE_URL", default=None):
    DATABASES = {
        "default": env.db(),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": env("DB_ENGINE", default="django.db.backends.sqlite3"),
            "NAME": env(
                "DB_NAME",
                default=os.path.join(BASE_DIR, "db.sqlite3"),
            ),
            "USER": env("DB_USER", default=""),
            "PASSWORD": env("DB_PASSWORD", default=""),
            "HOST": env("DB_HOST", default=""),
            "PORT": env("DB_PORT", default=""),
        }
    }

# Connection persistence for better performance
DATABASES["default"]["CONN_MAX_AGE"] = env.int("DB_CONN_MAX_AGE", default=60)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


LANGUAGES = [
    ("af", "Afrikaans"),
    ("ar", "Arabic"),
    ("ast", "Asturian"),
    ("az", "Azerbaijani"),
    ("bg", "Bulgarian"),
    ("be", "Belarusian"),
    ("bn", "Bengali"),
    ("br", "Breton"),
    ("bs", "Bosnian"),
    ("ca", "Catalan"),
    ("ckb", "Central Kurdish (Sorani)"),
    ("cs", "Czech"),
    ("cy", "Welsh"),
    ("da", "Danish"),
    ("de", "German"),
    ("dsb", "Lower Sorbian"),
    ("el", "Greek"),
    ("en", "English"),
    ("en-au", "Australian English"),
    ("en-gb", "British English"),
    ("eo", "Esperanto"),
    ("es", "Spanish"),
    ("es-ar", "Spanish, Argentina"),
    ("es-co", "Spanish, Colombia"),
    ("es-mx", "Spanish, Mexico"),
    ("es-ni", "Spanish, Nicaragua"),
    ("es-ve", "Spanish, Venezuela"),
    ("et", "Estonian"),
    ("eu", "Basque"),
    ("fa", "Persian"),
    ("fi", "Finnish"),
    ("fr", "French"),
    ("fy", "Frisian"),
    ("ga", "Irish"),
    ("gd", "Scottish Gaelic"),
    ("gl", "Galician"),
    ("he", "Hebrew"),
    ("hi", "Hindi"),
    ("hr", "Croatian"),
    ("hsb", "Upper Sorbian"),
    ("hu", "Hungarian"),
    ("hy", "Armenian"),
    ("ia", "Interlingua"),
    ("id", "Indonesian"),
    ("ig", "Igbo"),
    ("io", "Ido"),
    ("is", "Icelandic"),
    ("it", "Italian"),
    ("ja", "Japanese"),
    ("ka", "Georgian"),
    ("kab", "Kabyle"),
    ("kk", "Kazakh"),
    ("km", "Khmer"),
    ("kn", "Kannada"),
    ("ko", "Korean"),
    ("ky", "Kyrgyz"),
    ("lb", "Luxembourgish"),
    ("lt", "Lithuanian"),
    ("lv", "Latvian"),
    ("mk", "Macedonian"),
    ("mn", "Mongolian"),
    ("mr", "Marathi"),
    ("ms", "Malay"),
    ("my", "Burmese"),
    ("nb", "Norwegian Bokmål"),
    ("ne", "Nepali"),
    ("nl", "Dutch"),
    ("nn", "Norwegian Nynorsk"),
    ("os", "Ossetian"),
    ("pa", "Punjabi"),
    ("pl", "Polish"),
    ("pt", "Portuguese"),
    ("pt-br", "Portuguese, Brazilian"),
    ("ro", "Romanian"),
    ("ru", "Russian"),
    ("sk", "Slovak"),
    ("sl", "Slovenian"),
    ("sq", "Albanian"),
    ("sr", "Serbian (Cyrillic)"),
    ("sr-latn", "Serbian (Latin)"),
    ("sv", "Swedish"),
    ("sw", "Swahili"),
    ("ta", "Tamil"),
    ("te", "Telugu"),
    ("tg", "Tajik"),
    ("th", "Thai"),
    ("tk", "Turkmen"),
    ("tr", "Turkish"),
    ("tt", "Tatar"),
    ("udm", "Udmurt"),
    ("uk", "Ukrainian"),
    ("ur", "Urdu"),
    ("uz", "Uzbek"),
    ("vi", "Vietnamese"),
    ("zh-hans", "Chinese Simplified"),
    ("zh-hant", "Chinese Traditional"),
]

# -----------------------------------------------------------------------------
# Localization
# -----------------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
USE_I18N = True
USE_TZ = True
LOCALE_PATHS = [BASE_APP_DIR / "locale"]

# This will ignore browser language preferences
LANGUAGE_COOKIE_NAME = "django_language"
LANGUAGE_COOKIE_AGE = 31536000  # 1 year
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_PATH = "/"
LANGUAGE_COOKIE_SECURE = False
LANGUAGE_COOKIE_HTTPONLY = False
LANGUAGE_COOKIE_SAMESITE = "Lax"


# -----------------------------------------------------------------------------
# Authentication & Defaults
# -----------------------------------------------------------------------------
LOGIN_URL = "/login/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "horilla_core.HorillaUser"

# -----------------------------------------------------------------------------
# Email
# -----------------------------------------------------------------------------
EMAIL_BACKEND = "horilla_mail.horilla_backends.HorillaDefaultMailBackend"

DEFAULT_HOME_REDIRECT = "/dashboard/?section=home"

CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://127.0.0.1:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

TIME_ZONE = "UTC"

AUDITLOG_INCLUDE_ALL_MODELS = True
AUDITLOG_EXCLUDE_TRACKING_MODELS = (
    "horilla_core.RecentlyViewed",
    "horilla_core.ActiveTab",
    "horilla_core.ListColumnVisibility",
)


DB_INIT_PASSWORD = env(
    "DB_INIT_PASSWORD", default="d3f6a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d"
)


ALLOWED_LANGUAGES = [
    ("en", "English", "usa.webp"),
    ("ar", "Arabic", "ar.png"),
    ("de", "German", "german.jpeg"),
    ("fr", "French", "france.webp"),
]
