# Generated by Django 5.2.3 on 2025-11-20 05:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("horilla_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Folder Name")),
                ("is_favourite", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_reports.reportfolder",
                        verbose_name="Folder",
                    ),
                ),
                (
                    "report_folder_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Folder Owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Updated At"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Report Name")),
                ("selected_columns", models.TextField(blank=True)),
                ("row_groups", models.TextField(blank=True)),
                ("column_groups", models.TextField(blank=True)),
                ("aggregate_columns", models.TextField(blank=True)),
                ("filters", models.TextField(blank=True)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("column", "Column Chart"),
                            ("line", "Line Chart"),
                            ("pie", "Pie Chart"),
                            ("funnel", "Funnel"),
                            ("bar", "Bar Chart"),
                            ("donut", "Donut"),
                            ("stacked_vertical", "Stacked Vertical Chart"),
                            ("stacked_horizontal", "Stacked Horizontal Chart"),
                            ("scatter", "Scatter Chart"),
                        ],
                        default="bar",
                        max_length=20,
                    ),
                ),
                (
                    "chart_field",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Chart Field",
                    ),
                ),
                (
                    "chart_field_stacked",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Secondary Field",
                    ),
                ),
                ("is_favourite", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        limit_choices_to={
                            "model__in": [
                                "account",
                                "contact",
                                "lead",
                                "campaign",
                                "opportunity",
                            ]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_core.horillacontenttype",
                        verbose_name="Module",
                    ),
                ),
                (
                    "report_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Report Owner",
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horilla_reports.reportfolder",
                        verbose_name="Folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
            },
        ),
    ]
