# Generated by Django 4.2.23 on 2025-11-24 09:10

from django.db import migrations, models
import django.db.models.deletion
import horilla_reports.methods


class Migration(migrations.Migration):
    dependencies = [
        ("horilla_core", "0002_horillaaboutsystem"),
        ("horilla_reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="module",
            field=models.ForeignKey(
                limit_choices_to=horilla_reports.methods.limit_content_types,
                on_delete=django.db.models.deletion.CASCADE,
                to="horilla_core.horillacontenttype",
                verbose_name="Module",
            ),
        ),
    ]
